ServiceType: private
AllowedRegions:
- ap-southeast-1
ArtifactSourceType: DockerCompose
RepoName: JJGGu/authorizer
DockerComposeEnvPath: .env.test
RegionId: cn-hangzhou
CustomParameters: ''
DockerComposeYamlPath: docker-compose.yaml
Owner: JJGGu
Branch: main
Platform: github
