RuntimeType: Container
ServiceType: private
ArtifactSourceType: DockerCompose
ServiceBuildRegion: ap-southeast-1
RepoName: JJGGu/authorizer
DockerComposeEnvPath: .env.test
RegionId: cn-hangzhou
CustomParameters: ''
DockerComposeYamlPath: docker-compose.yaml
Owner: JJGGu
Branch: main
Platform: github
